[build]
command = """
mkdir functions &&
cargo build --release &&
cp target/release/image_gen functions/
"""
publish = "public"
functions = "functions"

[functions]
included_files = ["crates/image_gen/fonts/*"]
